#!/usr/bin/env sh

# setNpmRegistry
setNpmRegistry() {
  # 接受函数入参
  if [ $1 == 'taobao' ]
  then
    npm config set registry https://registry.npm.taobao.org
    echo 'switch to taobao registry'
  else
    npm config set registry http://npm.intra.xiaojukeji.com
    echo 'switch to didi registry'
  fi
}

# 接受命令行参数
setNpmRegistry $1
